apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-loki-config
  namespace: monitoring
data:
  local-config.yaml: |
    auth_enabled: {{ .Values.config.auth_enabled }}
    server:
      http_listen_port: {{ .Values.config.server.http_listen_port }}
    common:
      path_prefix: {{ .Values.config.common.path_prefix }}
      storage:
        filesystem:
          chunks_directory: {{ .Values.config.common.storage.filesystem.chunks_directory }}
          rules_directory: {{ .Values.config.common.storage.filesystem.rules_directory }}
    schema_config:
      configs:
        {{- toYaml .Values.config.schema_config.configs | nindent 8 }}
    storage_config:
      boltdb_shipper:
        {{- toYaml .Values.config.storage_config.boltdb_shipper | nindent 8 }}
      filesystem:
        {{- toYaml .Values.config.storage_config.filesystem | nindent 8 }}
    limits_config:
      {{- toYaml .Values.config.limits_config | nindent 6 }}
      
    # Single instance mode configuration
    target: all
    
    # Use memberlist instead of Consul for ring
    memberlist:
      join_members:
        - 127.0.0.1
    
    # Configure distributor, ingester and querier to use inmemory ring store
    distributor:
      ring:
        kvstore:
          store: inmemory
    
    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 30m
      chunk_retain_period: 1m
    
    frontend:
      max_outstanding_per_tenant: 4096
      
    querier:
      engine:
        timeout: 5m 