image:
  repository: grafana/loki
  tag: "2.9.2"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3100

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector:
  role: monitoring

persistence:
  enabled: true
  size: 5Gi
  storageClass: "gp2"

config:
  auth_enabled: false
  server:
    http_listen_port: 3100
  common:
    path_prefix: /loki
    storage:
      filesystem:
        chunks_directory: /loki/chunks
        rules_directory: /loki/rules
  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/cache
      cache_ttl: 24h
      shared_store: filesystem
    filesystem:
      directory: /loki/chunks

  limits_config:
    retention_period: 744h  # 31 days
    max_query_length: 721h
    split_queries_by_interval: 24h
    ingestion_rate_mb: 4
    ingestion_burst_size_mb: 6
    per_stream_rate_limit: 10MB
    per_stream_rate_limit_burst: 50MB 