apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.alertmanager.replicas | default 1 }}
  serviceAccountName: alertmanager
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  resources:
    requests:
      memory: 200Mi
      cpu: 100m
    limits:
      memory: 400Mi
      cpu: 200m
  # 영구 저장소 대신 임시 저장소 사용
  # storage:
  #   volumeClaimTemplate:
  #     spec:
  #       storageClassName: gp2
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: {{ .Values.alertmanager.persistence.size | default "2Gi" }}
  alertmanagerConfigSelector:
    matchLabels:
      app.kubernetes.io/name: alertmanager-config 