apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-recording-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: recording-rules
spec:
{{ (.Files.Glob "recording-rules/*.yaml").AsConfig | indent 2 }} 