apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-critical-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: alert-rules
spec:
  groups:
  {{- range $path, $_ := .Files.Glob "alerts/*.yaml" }}
  {{- $content := $.Files.Get $path }}
  {{- tpl ($content | replace "$labels" "$$labels") $ | nindent 2 }}
  {{- end }} 