apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-critical-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: alert-rules
spec:
{{ (.Files.Glob "alerts/*.yaml").AsConfig | indent 2 }} 