apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-recording-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: recording-rules
spec:
  groups:
  {{- range $path, $_ := .Files.Glob "recording-rules/*.yaml" }}
  {{- $content := $.Files.Get $path }}
  {{- tpl ($content | replace "$__rate_interval" "$$__rate_interval") $ | nindent 2 }}
  {{- end }} 