apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-recording-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: recording-rules
spec:
  groups:
  - name: node-recording-rules
    rules:
    - record: node:cpu_utilization:avg5m
      expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
    
    - record: node:memory_utilization:percent
      expr: 100 * (1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes))
    
    - record: node:disk_utilization:percent
      expr: 100 * (1 - node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})
  
  - name: service-recording-rules
    rules:
    - record: service:request_latency:p99
      expr: histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service, namespace))
    
    - record: service:request_latency:p95
      expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service, namespace))
    
    - record: service:request_latency:p50
      expr: histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service, namespace)) 