apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-recording-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: prometheus
    role: recording-rules
spec:
  groups:
  {{- range $path, $_ := .Files.Glob "recording-rules/*.yaml" }}
  - name: {{ $path | base | trimSuffix ".yaml" }}
    rules:
{{ $.Files.Get $path | indent 4 }}
  {{- end }} 