---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prometheus-operator
spec:
  selector:
    app.kubernetes.io/name: prometheus-operator
  ports:
  - name: http
    port: 8080
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prometheus
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app.kubernetes.io/name: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9093
    targetPort: web
  selector:
    app.kubernetes.io/name: alertmanager 