---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prometheus-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prometheus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: alertmanager 