apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karpenter-monitor
  namespace: monitoring
  labels:
    app: prometheus
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: karpenter
  namespaceSelector:
    matchNames:
      - karpenter
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics 