# 백엔드 서비스 URL (내부 테스트용)
targetUrl: "http://backend-service.backend.svc.cluster.local"

# 외부 접속 테스트를 위한 설정
# 클러스터 외부에서 접근하는 테스트 시 아래 설정을 주석 해제하고 사용
# targetUrl: "https://wiary.site" # 외부 도메인 테스트
# 
# 외부 접속 테스트 시 주의사항:
# 1. 인그레스/ALB가 올바르게 설정되어 있어야 합니다
# 2. 백엔드 서비스가 외부에서 접근 가능해야 합니다
# 3. HTTPS 사용 시 인증서가 유효해야 합니다

# 테스트할 엔드포인트
endpoints:
  - path: "/health"
    method: "GET"
  - path: "/metrics"
    method: "GET"
  - path: "/ping"
    method: "GET"

# 테스트 설정
test:
  duration:
    rampUp: "30s"
    steady: "2m"
    rampDown: "30s"
  vus: 30  # 가상 사용자 수

# K6 메트릭 전송 설정
output:
  loki:
    enabled: false  # 필요 없음, Fluent Bit가 로그 수집
  prometheus:
    enabled: true   # 메트릭 수집을 위해 활성화
    remoteWriteUrl: "http://prometheus-kube-prometheus-prometheus.monitoring:9090/api/v1/write"

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 2000m
    memory: 1Gi