# 백엔드 서비스 URL
targetUrl: "http://localhost:8080"  # 테스트용 임시 URL (실제 서비스로 변경 필요)

# 테스트할 엔드포인트
endpoints:
  - path: "/health"
    method: "GET"
  - path: "/metrics"
    method: "GET"
  - path: "/ping"
    method: "GET"

# 테스트 설정
test:
  duration:
    rampUp: "30s"
    steady: "2m"
    rampDown: "30s"
  vus: 30  # 가상 사용자 수

# K6 메트릭 전송 설정
output:
  loki:
    enabled: false  # 필요 없음, Fluent Bit가 로그 수집
  json:
    enabled: false  # 필요 없음, Fluent Bit가 로그 수집
  prometheus:
    enabled: true   # 메트릭 수집을 위해 활성화
    remoteWriteUrl: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/remote_write"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi