groups:
  - name: kubernetes-application-alerts
    rules:
    # API 응답 시간 관련 알림
    - alert: APIHighResponseTime
      expr: app:http_requests_latency:p95_rate5m > 1
      for: 10m
      labels:
        severity: warning
        type: application
      annotations:
        summary: "API 높은 응답 시간: {{ $labels.namespace }}/{{ $labels.service }}"
        description: "서비스 {{ $labels.namespace }}/{{ $labels.service }}의 95% API 응답 시간이 1초를 초과합니다. (현재 값: {{ $value }}초)"
    
    - alert: APICriticalResponseTime
      expr: app:http_requests_latency:p95_rate5m > 3
      for: 5m
      labels:
        severity: critical
        type: application
      annotations:
        summary: "API 심각한 응답 지연: {{ $labels.namespace }}/{{ $labels.service }}"
        description: "서비스 {{ $labels.namespace }}/{{ $labels.service }}의 95% API 응답 시간이 3초를 초과합니다. (현재 값: {{ $value }}초)"
    
    # 오류율 관련 알림
    - alert: APIHighErrorRate
      expr: app:http_requests_errors:ratio_rate5m > 0.05
      for: 5m
      labels:
        severity: warning
        type: application
      annotations:
        summary: "API 높은 오류율: {{ $labels.namespace }}/{{ $labels.service }}"
        description: "서비스 {{ $labels.namespace }}/{{ $labels.service }}의 오류율이 5%를 초과합니다. (현재 값: {{ $value | humanizePercentage }})"
    
    - alert: APICriticalErrorRate
      expr: app:http_requests_errors:ratio_rate5m > 0.2
      for: 5m
      labels:
        severity: critical
        type: application
      annotations:
        summary: "API 심각한 오류율: {{ $labels.namespace }}/{{ $labels.service }}"
        description: "서비스 {{ $labels.namespace }}/{{ $labels.service }}의 오류율이 20%를 초과합니다. (현재 값: {{ $value | humanizePercentage }})"
    
    # 특정 엔드포인트 관련 알림
    - alert: CriticalAPIEndpointHighErrorRate
      expr: app:api_requests_errors:ratio_rate5m{uri=~".*(login|payment|checkout).*"} > 0.01
      for: 5m
      labels:
        severity: critical
        type: application
      annotations:
        summary: "중요 API 엔드포인트 오류: {{ $labels.namespace }}/{{ $labels.service }} - {{ $labels.uri }}"
        description: "중요 엔드포인트 {{ $labels.uri }}의 오류율이 1%를 초과합니다. (현재 값: {{ $value | humanizePercentage }})"
    
    # 서비스 가용성 관련 알림
    - alert: ServiceUnavailable
      expr: service:availability:ratio < 0.99
      for: 5m
      labels:
        severity: critical
        type: application
      annotations:
        summary: "서비스 가용성 저하: {{ $labels.namespace }}/{{ $labels.service }}"
        description: "서비스 {{ $labels.namespace }}/{{ $labels.service }}의 가용성이 99% 미만입니다. (현재 값: {{ $value | humanizePercentage }})"
    
    # 애플리케이션 리소스 사용 관련 알림
    - alert: PodCPUUsageHigh
      expr: pod:cpu_utilization:percent > 80
      for: 15m
      labels:
        severity: warning
        type: application
      annotations:
        summary: "Pod CPU 사용량 높음: {{ $labels.namespace }}/{{ $labels.pod }}"
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }}의 CPU 사용량이 15분 이상 80%를 초과했습니다. (현재 값: {{ $value }}%)"
    
    - alert: PodMemoryUsageHigh
      expr: pod:memory_utilization:percent > 80
      for: 15m
      labels:
        severity: warning
        type: application
      annotations:
        summary: "Pod 메모리 사용량 높음: {{ $labels.namespace }}/{{ $labels.pod }}"
        description: "Pod {{ $labels.namespace }}/{{ $labels.pod }}의 메모리 사용량이 15분 이상 80%를 초과했습니다. (현재 값: {{ $value }}%)"
    
    # 트래픽 관련 알림
    - alert: HighTrafficSpike
      expr: rate(app:http_requests:rate5m[5m]) > 2 * rate(app:http_requests:rate5m[30m] offset 5m)
      for: 5m
      labels:
        severity: warning
        type: application
      annotations:
        summary: "트래픽 급증: {{ $labels.namespace }}/{{ $labels.service }}"
        description: "서비스 {{ $labels.namespace }}/{{ $labels.service }}의 트래픽이 평소보다 2배 이상 급증했습니다."
