# Prometheus 서버 기본 설정
server:
  retention: 1d  # 데이터 보존 기간 1일로 줄임
  # 리소스 요청 더 최적화
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi
  
  # 노드 셀렉터 설정 - 모니터링 노드에 스케줄링
  nodeSelector:
    eks.amazonaws.com/nodegroup: monitoring-node-group
  
  # 영구 스토리지 사용 (EBS)
  persistentVolume:
    enabled: true  # PVC 활성화
    size: 8Gi
    storageClass: "gp3"  # AWS EBS CSI 드라이버 사용
  
  # 보안 설정
  securityContext:
    runAsUser: 65534
    runAsNonRoot: true
    fsGroup: 65534
  
# Prometheus 스크레이핑 설정
# 기본적으로 kubernetes-service-endpoints, kubernetes-pods 등을 자동으로 발견하도록 설정
serviceDiscovery:
  enabled: true

# Prometheus 서버 상세 설정
prometheus:
  prometheusSpec:
    # Replica 설정 - 하나만 사용
    replicas: 1
    
    # 리소스 요청 더 최적화
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi
    
    # PrometheusRule 선택자 설정 (중요: 알림 및 레코딩 규칙 연결)
    ruleSelector:
      matchExpressions:
      - key: app
        operator: In
        values:
        - prometheus
      - key: role
        operator: In
        values:
        - alert-rules
        - recording-rules
    
    # Pod 업데이트 전략
    updateStrategy:
      type: RollingUpdate
    
    # 파드 중단 예산 (PDB) - 비활성화
    podDisruptionBudget:
      enabled: false
    
    # ServiceMonitor 선택자 설정
    serviceMonitorSelector:
      matchLabels:
        app: prometheus
    
    # 외부 라벨 설정
    externalLabels:
      cluster: production
      environment: eks
      
    # 노드 셀렉터 설정 - 모니터링 노드 그룹에 스케줄링
    nodeSelector:
      eks.amazonaws.com/nodegroup: monitoring-node-group
    
    # EBS 볼륨 사용 - 영구 데이터 저장
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp3
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi

# 알림 설정
alertmanager:
  enabled: true
  # AlertManager 상세 설정
  alertmanagerSpec:
    # Replica 설정
    replicas: 1
    
    # 리소스 요청 더 최적화
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 50m
        memory: 128Mi
    
    # PDB 비활성화
    podDisruptionBudget:
      enabled: false
    
    # Pod 업데이트 전략
    updateStrategy:
      type: RollingUpdate
    
    # 트래픽 라우팅
    routePrefix: /alertmanager
  
  # 영구 스토리지 설정 (EBS)
  persistence:
    enabled: true
    size: 2Gi
    storageClass: "gp3"  # AWS EBS CSI 드라이버 사용
  
  # 노드 셀렉터 설정 - 모니터링 노드 그룹에 스케줄링
  nodeSelector:
    eks.amazonaws.com/nodegroup: monitoring-node-group
  
  # 알림 라우팅 설정
  config:
    route:
      group_by: ['job', 'alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'
  
# Prometheus Operator 설정
prometheusOperator:
  enabled: true
  
  # 리소스 요청 더 최적화
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 50m
      memory: 128Mi
  
  # 노드 셀렉터 설정 - 모니터링 노드에 스케줄링
  nodeSelector:
    eks.amazonaws.com/nodegroup: monitoring-node-group

# 기본 스크레이퍼 설정 - 간격 증가로 부하 감소
scrapeInterval: 300s
evaluationInterval: 300s

# 노드 익스포터 설정
nodeExporter:
  enabled: true
  # 리소스 요청 더 최적화
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi

# kube-state-metrics 설정
kubeStateMetrics:
  enabled: true
  # Replica 설정
  replicas: 1
  
  # 리소스 요청 더 최적화
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 50m
      memory: 64Mi
  
  # 노드 셀렉터 설정 - 모니터링 노드에 스케줄링
  nodeSelector:
    eks.amazonaws.com/nodegroup: monitoring-node-group

# 최적화 설정
extraFlags:
  - "storage.tsdb.wal-compression"  # WAL 압축 활성화

# 불필요한 컴포넌트 비활성화
grafana:
  enabled: false
  
  # 노드 셀렉터 설정 - 모니터링 노드에 스케줄링
  nodeSelector:
    eks.amazonaws.com/nodegroup: monitoring-node-group

defaultRules:
  create: false  # 자체 규칙을 사용하므로 기본 규칙 비활성화

# 필요한 쿠버네티스 컴포넌트만 활성화
kubelet:
  enabled: true

# CoreDNS 활성화
coreDns:
  enabled: true

# 불필요한 컴포넌트는 비활성화 상태 유지
kubeApiServer:
  enabled: false

kubeDns:
  enabled: false

kubeControllerManager:
  enabled: false

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: false 