apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush           {{ .Values.service.flush }}
        Log_Level       {{ .Values.service.logLevel }}
        Parsers_File    parsers.conf

    [INPUT]
        Name            tail
        Path            {{ .Values.input.tail.path }}
        Parser          {{ .Values.input.tail.parser }}
        Tag             {{ .Values.input.tail.tag }}

    [FILTER]
        Name            kubernetes
        Match           kube.*
        Merge_Log       on
        Keep_Log        off

# 헬스체크와 메트릭스 엔드포인트 로그 필터링
    [FILTER]
        Name            grep
        Match           kube.var.log.containers.backend-*
        Exclude         message Request: .* /health -
        Exclude         message Request: .* /metrics -

    [OUTPUT]
        Name            stdout
        Match           *
        
    [OUTPUT]
        Name            loki
        Match           *
        Host            {{ .Values.output.loki.host }}
        Port            {{ .Values.output.loki.port }}
        Labels          namespace=$kubernetes['namespace_name'],app=$kubernetes['labels']['app'],pod_name=$kubernetes['pod_name'],pod_hash=$kubernetes['labels']['pod-template-hash']
        {{- if .Values.output.loki.removeKeys }}
        Remove_Keys     {{ join "," .Values.output.loki.removeKeys }}
        {{- end }}
        Retry_Limit     5
        
  parsers.conf: |
    [PARSER]
        Name            docker
        Format          json
        Time_Key        time
        Time_Format     %Y-%m-%dT%H:%M:%S.%L
        Time_Keep       On
