apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush           {{ .Values.service.flush }}
        Log_Level       {{ .Values.service.logLevel }}
        Parsers_File    parsers.conf

    [INPUT]
        Name            tail
        Path            {{ .Values.input.tail.path }}
        Parser          {{ .Values.input.tail.parser }}
        Tag             {{ .Values.input.tail.tag }}

    [FILTER]
        Name            kubernetes
        Match           kube.*
        Merge_Log       {{ .Values.filters.kubernetes.mergeLog }}
        Keep_Log        {{ .Values.filters.kubernetes.keepLog }}
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        
        {{- if and .Values.filters.kubernetes.allowNamespaces (gt (len .Values.filters.kubernetes.allowNamespaces) 0) }}
        Kube_Tag_Prefix kube.var.log.containers.
        Regex_Parser    kube
        {{- range .Values.filters.kubernetes.allowNamespaces }}
        Kube_Namespace  {{ . }}
        {{- end }}
        {{- end }}

    [OUTPUT]
        Name            stdout
        Match           *
        
  parsers.conf: |
    [PARSER]
        Name            docker
        Format          json
        Time_Key        time
        Time_Format     %Y-%m-%dT%H:%M:%S.%L
        Time_Keep       On
