apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush           {{ .Values.service.flush }}
        Log_Level       {{ .Values.service.logLevel }}
        Parsers_File    parsers.conf

    [INPUT]
        Name            tail
        Path            {{ .Values.input.tail.path }}
        Parser          docker
        Tag             kube.*

    [FILTER]
        Name            kubernetes
        Match           kube.*
        Merge_Log       on
        Keep_Log        off

    # 임시 로그 파일 출력
    [OUTPUT]
        Name            file
        Match           kube.*
        Path            /tmp/fluent-bit.log
        Format          json
  parsers.conf: |
    [PARSER]
        Name            docker
        Format          json
        Time_Key        time
        Time_Format     %Y-%m-%dT%H:%M:%S.%L
        Time_Keep       On
