apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush           {{ .Values.service.flush }}
        Log_Level       {{ .Values.service.logLevel }}
        Parsers_File    parsers.conf

    [INPUT]
        Name            tail
        Path            {{ .Values.input.tail.path }}
        Parser          {{ .Values.input.tail.parser }}
        Tag             {{ .Values.input.tail.tag }}

    [FILTER]
        Name            kubernetes
        Match           kube.*
        Merge_Log       on
        Keep_Log        off

    [OUTPUT]
        Name            stdout
        Match           *
        
    [OUTPUT]
        Name            loki
        Match           *
        Host            {{ .Values.output.loki.host }}
        Port            {{ .Values.output.loki.port }}
        Labels          job=fluent-bit
        {{- range .Values.output.loki.labels }}
        Labels          {{ . }}
        {{- end }}
        {{- if .Values.output.loki.removeKeys }}
        Remove_Keys     {{ join "," .Values.output.loki.removeKeys }}
        {{- end }}
        Retry_Limit     -1
        
  parsers.conf: |
    [PARSER]
        Name            docker
        Format          json
        Time_Key        time
        Time_Format     %Y-%m-%dT%H:%M:%S.%L
        Time_Keep       On
