apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush           {{ .Values.service.flush }}
        Log_Level       {{ .Values.service.logLevel }}
        Parsers_File    parsers.conf

    [INPUT]
        Name            tail
        Path            {{ .Values.input.tail.path }}
        Parser          {{ .Values.input.tail.parser }}
        Tag             {{ .Values.input.tail.tag }}

    [OUTPUT]
        Name            file
        Match           *
        Path            /tmp/fluent-bit.log
        Format          json_lines
        
  parsers.conf: |
    [PARSER]
        Name            docker
        Format          json
        Time_Key        time
        Time_Format     %Y-%m-%dT%H:%M:%S.%L
        Time_Keep       On
