apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush           {{ .Values.service.flush }}
        Log_Level       {{ .Values.service.logLevel }}
        Parsers_File    parsers.conf

    [INPUT]
        Name            tail
        Path            {{ .Values.input.tail.path }}
        Parser          {{ .Values.input.tail.parser }}
        Tag             {{ .Values.input.tail.tag }}
        {{- if .Values.input.tail.mem_buf_limit }}
        Mem_Buf_Limit   {{ .Values.input.tail.mem_buf_limit }}
        {{- end }}
        {{- if .Values.input.tail.skip_long_lines }}
        Skip_Long_Lines {{ .Values.input.tail.skip_long_lines }}
        {{- end }}
        {{- if .Values.input.tail.db }}
        DB              {{ .Values.input.tail.db }}
        DB.Sync         Normal
        {{- end }}

    [FILTER]
        Name            kubernetes
        Match           kube.*
        Merge_Log       {{ .Values.filters.kubernetes.mergeLog }}
        Keep_Log        {{ .Values.filters.kubernetes.keepLog }}
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        
        {{- if .Values.filters.kubernetes.allowNamespaces }}
        Kube_Tag_Prefix kube.var.log.containers.
        Regex_Parser    kube
        {{- range .Values.filters.kubernetes.allowNamespaces }}
        Kube_Namespace  {{ . }}
        {{- end }}
        {{- end }}

    [FILTER]
        Name            grep
        Match           kube.*
        {{- range .Values.filters.grep.rules }}
        {{- if .exclude }}
        Exclude         {{ .key }} {{ .pattern }}
        {{- else }}
        Regex           {{ .key }} {{ .pattern }}
        {{- end }}
        {{- end }}

    [OUTPUT]
        Name            loki
        Match           kube.*
        Host            {{ .Values.output.loki.host }}
        Port            {{ .Values.output.loki.port }}
        Labels          {{ range $index, $label := .Values.output.loki.labels }}{{if $index}},{{end}}{{ $label }}{{ end }}
        Remove_Keys     {{ range $index, $key := .Values.output.loki.removeKeys }}{{if $index}},{{end}}{{ $key }}{{ end }}
        
    # 임시 로그 파일 출력 (Loki가 준비될 때까지)
    [OUTPUT]
        Name            file
        Match           kube.*
        Path            /var/fluent-bit/state/logs.json
        Format          json_lines
        
  parsers.conf: |
    [PARSER]
        Name            docker
        Format          json
        Time_Key        time
        Time_Format     %Y-%m-%dT%H:%M:%S.%L
        Time_Keep       On
