apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluent-bit
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-fluent-bit
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fluent-bit
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fluent-bit
    spec:
      serviceAccountName: {{ .Release.Name }}-fluent-bit
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: fluent-bit
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.metrics.enabled }}
        ports:
        - containerPort: {{ .Values.metrics.port }}
          name: metrics
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers 