apiVersion: v1
kind: Service
metadata:
  name: aws-load-balancer-controller-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: aws-load-balancer-controller
  type: ClusterIP 