image:
  repository: fluent/fluent-bit
  tag: 2.2.0
  pullPolicy: IfNotPresent

namespace: monitoring

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# 배포 설정
tolerations:
  - operator: Exists

nodeSelector:
  role: monitoring  # 모니터링 노드에만 배포

# 메트릭 설정
metrics:
  enabled: true
  port: 2020
  
# 로그 수집 설정
service:
  flush: 30
  logLevel: info
  
# 로그 수집 대상
input:
  tail:
    path: /var/log/containers/*.log
    parser: docker
    tag: kube.*

# Kubernetes 메타데이터 추가 및 필터링
filters:
  kubernetes:
    enabled: true
    keepLog: false
    mergeLog: true
    # 백엔드 네임스페이스만 수집
    allowNamespaces:
      - backend

  # 중요 로그 필터링
  grep:
    enabled: true
    rules:
      # 에러 및 경고 로그 수집
      - key: log
        pattern: ERROR|Error|error|WARN|Warn|warn|FATAL|Fatal|fatal|CRITICAL|Critical|critical
      
      # 성능 관련 로그 수집
      - key: log
        pattern: timeout|Timeout|slow query|performance|latency|duration
      
      # 보안 관련 로그 수집
      - key: log
        pattern: unauthorized|Unauthorized|forbidden|Forbidden|invalid token|Invalid Token|authentication failed
      
      # 불필요한 로그 제외
      - key: log
        pattern: /health|/ping|/metrics
        exclude: true

# Loki로 로그 전송
output:
  loki:
    host: loki
    port: 3100
    labels:
      - namespace=$kubernetes['namespace_name']
      - app=$kubernetes['labels']['app']
      - pod_name=$kubernetes['pod_name']
      - pod_hash=$kubernetes['labels']['pod-template-hash']
    removeKeys:
      - kubernetes
      - stream
      - time
