apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    # 공식 Helm 차트 사용
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.7.1
    # GitHub 레포지토리의 파일 참조 설정
    helm:
      # CRD는 이미 설치되어 있으므로 건너뜁니다
      skipCrds: true
      
      # GitHub 저장소의 values.yaml 파일 참조
      valueFiles:
        - https://raw.githubusercontent.com/AWS-Cloud-FinalProject/monitoring/develop/prometheus/values.yaml
      
      # 최소한의 인라인 설정만 유지
      values: |
        # 리소스 이름 단순화 설정
        fullnameOverride: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true