apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    # Git 저장소의 Helm 차트 사용
    repoURL: https://github.com/AWS-Cloud-FinalProject/monitoring.git
    targetRevision: yong
    path: prometheus
    # Helm 설정
    helm:
      # CRD는 이미 설치되어 있으므로 건너뜁니다
      skipCrds: true
      
      # values.yaml을 상대 경로로 참조 (차트 내 파일)
      valueFiles:
        - values.yaml
      
      # 인라인 values로 기본 규칙 비활성화를 명시적으로 설정
      values: |
        # 리소스 이름 단순화 설정
        fullnameOverride: prometheus
        
        # 기본 규칙 직접 비활성화 (최상위 레벨에서)
        defaultRules:
          create: false
          rules:
            alertmanager: false
            etcd: false
            general: false
            k8s: false
            kubeApiserver: false
            kubeApiserverAvailability: false
            kubeApiserverError: false
            kubeApiserverSlos: false
            kubelet: false
            kubePrometheusGeneral: false
            kubePrometheusNodeAlerting: false
            kubePrometheusNodeRecording: false
            kubernetesAbsent: false
            kubernetesApps: false
            kubernetesResources: false
            kubernetesStorage: false
            kubernetesSystem: false
            kubeScheduler: false
            kubeStateMetrics: false
            network: false
            node: false
            prometheus: false
            prometheusOperator: false
            time: false
        
        # EKS에서 불필요한 컴포넌트 비활성화
        kubeControllerManager:
          enabled: false
        
        kubeScheduler:
          enabled: false
        
        kubeEtcd:
          enabled: false
        
        kubeProxy:
          enabled: false
        
        # 필요한 컴포넌트는 활성화
        kubelet:
          enabled: true
        
        coreDns:
          enabled: true
        
        kubeApiServer:
          enabled: false
        
        # 의존성 차트에 값 전달하는 방식 수정 (기존 설정 유지)
        kube-prometheus-stack:
          defaultRules:
            create: false
            rules:
              alertmanager: false
              etcd: false
              general: false
              k8s: false
              kubeApiserver: false
              kubeApiserverAvailability: false
              kubeApiserverError: false
              kubeApiserverSlos: false
              kubelet: false
              kubePrometheusGeneral: false
              kubePrometheusNodeAlerting: false
              kubePrometheusNodeRecording: false
              kubernetesAbsent: false
              kubernetesApps: false
              kubernetesResources: false
              kubernetesStorage: false
              kubernetesSystem: false
              kubeScheduler: false
              kubeStateMetrics: false
              network: false
              node: false
              prometheus: false
              prometheusOperator: false
              time: false
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true