apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-recording-rules
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AWS-Cloud-FinalProject/monitoring.git
    path: prometheus/recording-rules
    targetRevision: HEAD
    directory:
      recurse: false
      include: "critical-recording-rules.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true 