apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AWS-Cloud-FinalProject/monitoring.git
    chart: kube-prometheus-stack
    targetRevision: 45.7.1
    helm:
      valueFiles:
      - prometheus/values.yaml
      # Values.yaml에 없거나 오버라이드가 필요한 추가 설정만 여기에 정의
      values: |
        prometheus:
          prometheusSpec:
            # PrometheusRule CR 참조 설정 
            ruleSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - prometheus
              - key: role
                operator: In
                values:
                - alert-rules
                - recording-rules
        
        # AlertManager 알림 설정 
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['job', 'alertname', 'namespace']
              group_wait: 30s
              group_interval: 5m
              repeat_interval: 12h
              receiver: 'null'
              routes:
              - match:
                  alertname: Watchdog
                receiver: 'null'
            receivers:
            - name: 'null'
            # 실제 환경에서는 아래 예시처럼 알림 채널 추가 필요
            # - name: 'slack'
            #   slack_configs:
            #   - api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXX'
            #     channel: '#monitoring-alerts'
            #     send_resolved: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
