apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
  namespace: {{ .Release.Namespace }}
data:
  load-test.js: |
    import { sleep } from 'k6';
    
    export const options = {
      vus: 1,
      duration: '10s',
    };
    
    export default function () {
      // 아주 간단한 테스트 - 네트워크 연결 없이 단순 지연
      console.log("테스트 실행 중...");
      sleep(1);
    }
