apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test-script
  namespace: {{ .Release.Namespace }}
data:
  load-test.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';
    
    export const options = {
      vus: 1,
      duration: '10s',
    };
    
    export default function () {
      try {
        // 간단한 HTTP 요청 - 존재하는 서비스로 변경 필요
        const url = 'http://{{ .Release.Namespace }}-prometheus-kube-prometheus-prometheus.{{ .Release.Namespace }}:9090/';
        console.log(`Sending request to: ${url}`);
        const response = http.get(url);
        console.log(`Response status: ${response.status}`);
      } catch (e) {
        console.error(`Error: ${e.message}`);
      }
      
      sleep(1);
    }
