apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        args:
        - run
        {{- if and .Values.output.prometheus.enabled .Values.output.prometheus.remoteWriteUrl }}
        - --out
        - prometheus-remote-write=url={{ .Values.output.prometheus.remoteWriteUrl }}
        {{- end }}
        - /tests/load-test.js
        volumeMounts:
        - name: k6-test-script
          mountPath: /tests
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: k6-test-script
        configMap:
          name: k6-test-script
      restartPolicy: Never
  backoffLimit: 4
