apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
  namespace: {{ .Release.Namespace }}
spec:
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5656"
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest
        env:
        - name: K6_VERBOSE
          value: "true"
        args:
        - run
        {{- if .Values.output.prometheus.enabled }}
        - --out
        - prometheus-remote-write={{ .Values.output.prometheus.remoteWriteUrl }}
        {{- end }}
        - /tests/load-test.js
        volumeMounts:
        - name: k6-test-script
          mountPath: /tests
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: k6-test-script
        configMap:
          name: k6-test-script
      restartPolicy: Never
  backoffLimit: 3
