nodeExporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  # 메트릭 수집 최적화
  extraArgs:
    - --collector.disable=diskstats.device,netclass,netdev
    - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($|/)
